[platformio]
build_cache_dir = .pio/build_cache

[env:esp32dev]
platform = platformio/espressif32 @ ~6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
monitor_echo = true
lib_deps = 
	https://github.com/KiraFlux/KiraFlux-Toolkit.git@0.3.4

build_flags =
	-std=gnu++17


build_unflags =
	-std=gnu++11
