# Copyright (c) 2026 KiraFlux
# SPDX-License-Identifier: MIT
#
# KiraFlux Toolkit - Example Project Configuration
#
# PlatformIO configuration for ESP32 and native builds.
# All examples share common build flags and library paths.
# Repository: https://github.com/KiraFlux/KiraFlux-Toolkit

[platformio]
build_cache_dir = .pio/build_cache

default_envs = esp32dev


[env]
monitor_speed = 115200
monitor_echo = true

lib_deps = 
	https://github.com/KiraFlux/KiraFlux-Toolkit.git#dev
    okalachev/MAVLink@^2.0.22

build_flags = 
    -std=gnu++20
    -D NO_GLOBAL_INSTANCES
    -Wno-address-of-packed-member
    -fstack-usage
    -I .pio/libdeps/native/KiraFlux-Toolkit/src # platformio issue ?
    -I ../../src


[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino


[env:native]
platform = native
